apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: html-volume
          emptyDir: {}
      initContainers:
        - name: sidecar
          image: python:alpine
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
          command: ["sh", "-c"]
          args:
            - |
              echo "hello, world $(date)" > /usr/share/nginx/html/index.html;
      containers:
        - name: app
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
