apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-sidecar
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:jpa-penneo/test-sidecar.git
    targetRevision: main
    path: charts/
    helm:
      releaseName: test-sidecar

  destination:
    server: "https://kubernetes.default.svc"
    namespace: "default"
